# Generated by Django 5.2 on 2025-04-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标签标识')),
                ('description', models.TextField(blank=True, null=True, verbose_name='标签描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签图标')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='标签颜色')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='标签排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='链接标题')),
                ('url', models.URLField(unique=True, verbose_name='链接地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='链接描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='链接图标')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='链接排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.ManyToManyField(blank=True, related_name='links', to='navigation.tags', verbose_name='标签')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'db_table': 'links',
            },
        ),
    ]
