# Generated by Django 5.2 on 2025-04-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_links_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
