# Generated by Django 5.2 on 2025-04-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_rename_parent_id_links_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='parent',
        ),
        migrations.AddField(
            model_name='tags',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='navigation.tags', verbose_name='父级标签'),
        ),
    ]
